const $=s=>document.querySelector(s),state={rows:[],filtered:[]},avg=(a,k)=>a.length?a.reduce((s,r)=>s+(+r[k]||0),0)/a.length:0,fmt=n=>new Intl.NumberFormat('en-IN').format(Math.round(n));
function parse(t){const [h,...ls]=t.trim().split(/\r?\n/),k=h.split(',');return ls.map(l=>Object.fromEntries(k.map((x,i)=>[x,l.split(',')[i]])))}
function group(a,k){return a.reduce((o,r)=>((o[r[k]]??=[]).push(r),o),{})}
async function init(){theme();mobile();try{state.rows=parse(await fetch('data/hr_employees.csv').then(r=>r.text()));setup();render();$('#loading').hidden=true;$('#dashboard').hidden=false}catch(e){$('#loading').textContent='Unable to load workforce data.'}}
function setup(){for(const [id,key] of [['department','department'],['gender','gender'],['level','job_level']])[...new Set(state.rows.map(r=>r[key]))].sort().forEach(v=>$('#'+id).insertAdjacentHTML('beforeend',`<option>${v}</option>`));document.querySelectorAll('.filters select').forEach(x=>x.onchange=render);$('#reset').onclick=()=>{document.querySelectorAll('.filters select').forEach(x=>x.value='All');render()};$('#exportBtn').onclick=exportCSV}
function render(){state.filtered=state.rows.filter(r=>[['department','department'],['gender','gender'],['level','job_level'],['attrition','attrition']].every(([id,k])=>$('#'+id).value==='All'||r[k]===$('#'+id).value));kpis();departments();workforce();levels();risk();insights();trend()}
function kpis(){const r=state.filtered,exits=r.filter(x=>x.attrition==='Yes'),items=[['Headcount',r.length,'Active dataset'],['Attrition rate',(r.length?exits.length/r.length*100:0).toFixed(1)+'%','Employee exits'],['Average salary','₹'+fmt(avg(r,'monthly_income')),'Monthly income'],['Average tenure',avg(r,'years_at_company').toFixed(1)+' yrs','Company experience'],['Engagement',avg(r,'engagement_score').toFixed(1)+'/100','Workforce pulse'],['Performance',avg(r,'performance_rating').toFixed(2)+'/5','Average rating']];$('#overview').innerHTML=items.map(x=>`<article class="kpi"><small>${x[0]}</small><strong>${x[1]}</strong><em>${x[2]}</em></article>`).join('')}
function departments(){const a=Object.entries(group(state.filtered,'department')).map(([n,r])=>({n,v:r.length?r.filter(x=>x.attrition==='Yes').length/r.length*100:0})).sort((a,b)=>b.v-a.v),m=Math.max(...a.map(x=>x.v),1);$('#deptBars').innerHTML=a.map(x=>`<div class="bar"><span>${x.n}</span><div class="track"><div class="fill" style="width:${x.v/m*100}%"></div></div><strong>${x.v.toFixed(1)}%</strong></div>`).join('')}
function workforce(){const a=Object.entries(group(state.filtered,'department')).map(([n,r])=>({n,v:r.length})).sort((a,b)=>b.v-a.v),m=Math.max(...a.map(x=>x.v),1);$('#workforceBars').innerHTML=a.map(x=>`<div class="bar"><span>${x.n}</span><div class="track"><div class="fill" style="width:${x.v/m*100}%"></div></div><strong>${x.v}</strong></div>`).join('')}
function levels(){const a=Object.entries(group(state.filtered,'job_level')).map(([n,r])=>({n,perf:avg(r,'performance_rating'),salary:avg(r,'monthly_income'),eng:avg(r,'engagement_score')}));$('#levelCards').innerHTML=a.map(x=>`<div class="level-card"><strong>Level ${x.n}</strong><p>Performance ${x.perf.toFixed(2)}/5<br>Avg salary ₹${fmt(x.salary)}<br>Engagement ${x.eng.toFixed(0)}/100</p></div>`).join('')}
function score(r){let s=0;s+=r.overtime==='Yes'?25:0;s+=+r.job_satisfaction<=2?25:0;s+=+r.engagement_score<60?20:0;s+=+r.years_at_company<2?15:0;s+=+r.monthly_income<45000?10:0;s+=+r.performance_rating<3?5:0;return s}
function risk(){const a=state.filtered.map(r=>({...r,risk:score(r)})).sort((a,b)=>b.risk-a.risk).slice(0,12);$('#riskTable').innerHTML=a.map(r=>{const c=r.risk>=55?'high':r.risk>=30?'medium':'low';return `<tr><td><strong>${r.employee_id}</strong></td><td>${r.department}</td><td>${r.job_role}</td><td>${r.years_at_company} yrs</td><td>${r.overtime}</td><td>${r.job_satisfaction}/4</td><td class="risk ${c}">${c.toUpperCase()} · ${r.risk}</td></tr>`}).join('')}
function insights(){const r=state.filtered,depts=Object.entries(group(r,'department')).map(([n,x])=>({n,rate:x.filter(v=>v.attrition==='Yes').length/x.length*100})).sort((a,b)=>b.rate-a.rate),ot=r.filter(x=>x.overtime==='Yes'),no=r.filter(x=>x.overtime==='No'),otRate=ot.length?ot.filter(x=>x.attrition==='Yes').length/ot.length*100:0,noRate=no.length?no.filter(x=>x.attrition==='Yes').length/no.length*100:0,low=r.filter(x=>+x.engagement_score<60).length;const a=[['Retention priority',depts[0]?`${depts[0].n} has the highest filtered attrition at ${depts[0].rate.toFixed(1)}%. Review manager, role and pay patterns.`:'No data'],['Overtime signal',`Overtime attrition is ${otRate.toFixed(1)}% versus ${noRate.toFixed(1)}% without overtime. Rebalance workload where the gap is material.`],['Engagement watch',`${low} employees have engagement below 60. Prioritize manager check-ins, growth plans and pulse follow-up.`]];$('#insightGrid').innerHTML=a.map(x=>`<div class="insight"><strong>${x[0]}</strong><p>${x[1]}</p></div>`).join('')}
function trend(){const months=[...new Set(state.filtered.map(r=>r.review_month))].sort(),d=months.map(m=>{const a=state.filtered.filter(r=>r.review_month===m);return{m,v:a.length?a.filter(r=>r.attrition==='Yes').length/a.length*100:0}});draw($('#trend'),d)}
function draw(cv,d){const w=cv.clientWidth||700,h=250,q=devicePixelRatio||1;cv.width=w*q;cv.height=h*q;const c=cv.getContext('2d');c.scale(q,q);const css=getComputedStyle(document.documentElement),line=css.getPropertyValue('--line'),muted=css.getPropertyValue('--muted'),accent=css.getPropertyValue('--accent');c.clearRect(0,0,w,h);const p={l:38,r:12,t:15,b:30},mx=Math.max(...d.map(x=>x.v),1)*1.15;c.strokeStyle=line;c.fillStyle=muted;c.font='10px Inter';for(let i=0;i<5;i++){const y=p.t+(h-p.t-p.b)*i/4;c.beginPath();c.moveTo(p.l,y);c.lineTo(w-p.r,y);c.stroke();c.fillText((mx*(1-i/4)).toFixed(0)+'%',2,y+3)}const pts=d.map((x,i)=>({x:p.l+(w-p.l-p.r)*i/Math.max(1,d.length-1),y:p.t+(h-p.t-p.b)*(1-x.v/mx)}));c.beginPath();pts.forEach((x,i)=>i?c.lineTo(x.x,x.y):c.moveTo(x.x,x.y));c.strokeStyle=accent;c.lineWidth=3;c.stroke();d.forEach((x,i)=>{if(i%2===0){c.fillStyle=muted;c.fillText(x.m.slice(5),pts[i].x-11,h-8)}})}
function theme(){const t=$('#themeToggle');function set(x){document.documentElement.dataset.theme=x;localStorage.setItem('hr-theme',x);t.innerHTML=(x==='light'?'☾ <span>Dark mode</span>':'☀ <span>Light mode</span>');dispatchEvent(new Event('resize'))}set(localStorage.getItem('hr-theme')||(matchMedia('(prefers-color-scheme:light)').matches?'light':'dark'));t.onclick=()=>set(document.documentElement.dataset.theme==='light'?'dark':'light')}
function mobile(){const m=$('#mobileMenu'),s=$('#sidebar'),b=$('#backdrop'),close=()=>{s.classList.remove('open');b.classList.remove('show')};m.onclick=()=>{s.classList.toggle('open');b.classList.toggle('show')};b.onclick=close;document.querySelectorAll('nav a').forEach(a=>a.onclick=close)}
function exportCSV(){const h=Object.keys(state.rows[0]),csv=[h.join(','),...state.filtered.map(r=>h.map(k=>r[k]).join(','))].join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='hr_filtered_data.csv';a.click()}
addEventListener('resize',()=>state.filtered.length&&trend());init();
