const $=s=>document.querySelector(s),state={rows:[],filtered:[]},fmt=n=>new Intl.NumberFormat('en-IN').format(Math.round(n)),avg=(a,k)=>a.length?a.reduce((s,r)=>s+(+r[k]||0),0)/a.length:0,grp=(a,k)=>a.reduce((o,r)=>((o[r[k]]??=[]).push(r),o),{});
function csv(t){const [h,...ls]=t.trim().split(/\r?\n/),k=h.split(',');return ls.map(l=>Object.fromEntries(k.map((x,i)=>[x,l.split(',')[i]])))}
async function init(){ui();try{state.rows=csv(await fetch('data/hr_employees.csv').then(r=>r.text()));filters();render();$('#loading').hidden=true;$('#dashboard').hidden=false}catch(e){$('#loading').textContent='Unable to load HR dataset.'}}
function ui(){const root=document.documentElement,t=$('#themeToggle'),set=x=>{root.dataset.theme=x;localStorage.setItem('people-theme',x);t.textContent=x==='light'?'☾':'☀'};set(localStorage.getItem('people-theme')||'light');t.onclick=()=>set(root.dataset.theme==='light'?'dark':'light');$('#mobileMenu').onclick=()=>$('#mobileNav').classList.toggle('open');document.querySelectorAll('.mobile-nav a').forEach(a=>a.onclick=()=>$('#mobileNav').classList.remove('open'));$('#search').oninput=people;$('#exportBtn').onclick=exportData}
function filters(){for(const [id,k] of [['department','department'],['workMode','work_mode'],['level','job_level'],['gender','gender']])[...new Set(state.rows.map(r=>r[k]))].sort().forEach(v=>$('#'+id).insertAdjacentHTML('beforeend',`<option>${v}</option>`));document.querySelectorAll('.filterbar select').forEach(x=>x.onchange=render);$('#reset').onclick=()=>{document.querySelectorAll('.filterbar select').forEach(x=>x.value='All');render()}}
function render(){state.filtered=state.rows.filter(r=>[['department','department'],['workMode','work_mode'],['level','job_level'],['gender','gender']].every(([id,k])=>$('#'+id).value==='All'||r[k]===$('#'+id).value));metrics();retention();departments();talent();actions();people()}
function metrics(){const r=state.filtered,exit=r.filter(x=>x.attrition==='Yes').length,promo=r.filter(x=>x.promotion_eligible==='Yes').length;$('#headcount').textContent=fmt(r.length);$('#retentionKpi').textContent=(r.length?(1-exit/r.length)*100:0).toFixed(1)+'%';$('#engagementKpi').textContent=avg(r,'engagement_score').toFixed(0);$('#promotionKpi').textContent=(r.length?promo/r.length*100:0).toFixed(1)+'%'}
function retention(){const r=state.filtered,rate=r.length?r.filter(x=>x.attrition==='Yes').length/r.length*100:0;$('#attritionRate').textContent=rate.toFixed(1)+'% attrition';$('#donut').style.setProperty('--rate',rate+'%');$('#donut').querySelector('strong').textContent=rate.toFixed(1)+'%';const drivers=[['Overtime',x=>x.overtime==='Yes'],['Low satisfaction',x=>+x.job_satisfaction<=2],['Low engagement',x=>+x.engagement_score<60],['Early tenure',x=>+x.years_at_company<2]],vals=drivers.map(([n,f])=>{const a=r.filter(f);return{n,v:a.length?a.filter(x=>x.attrition==='Yes').length/a.length*100:0}}),m=Math.max(...vals.map(x=>x.v),1);$('#driverList').innerHTML=vals.map(x=>`<div class="driver"><span>${x.n}</span><div class="track"><div class="fill" style="width:${x.v/m*100}%"></div></div><strong>${x.v.toFixed(1)}%</strong></div>`).join('')}
function departments(){const a=Object.entries(grp(state.filtered,'department')).map(([n,r])=>({n,count:r.length,ret:100-r.filter(x=>x.attrition==='Yes').length/r.length*100})).sort((a,b)=>b.ret-a.ret),m=Math.max(...a.map(x=>x.count),1);$('#departmentRows').innerHTML=a.map(x=>`<div class="dept-row"><span>${x.n}</span><div class="track"><div class="fill" style="width:${x.count/m*100}%"></div></div><strong>${x.ret.toFixed(0)}%</strong></div>`).join('')}
function talent(){const r=state.filtered,modes=Object.entries(grp(r,'work_mode'));$('#modeCards').innerHTML=modes.map(([n,a])=>`<div class="mode"><strong>${avg(a,'engagement_score').toFixed(0)}</strong><small>${n}<br>${a.length} people</small></div>`).join('');const levels=Object.entries(grp(r,'job_level')).map(([n,a])=>({n,v:a.length?a.filter(x=>x.promotion_eligible==='Yes').length/a.length*100:0})),mx=Math.max(...levels.map(x=>x.v),1);$('#growthChart').innerHTML=levels.map(x=>`<div class="growth-col"><div class="growth-bar" style="height:${x.v/mx*115}px" title="${x.v.toFixed(1)}% eligible"></div>L${x.n}<br>${x.v.toFixed(0)}%</div>`).join('');$('#trainingAvg').textContent=avg(r,'training_hours').toFixed(0)+'h';const ds=Object.entries(grp(r,'department')).map(([n,a])=>({n:n.slice(0,4),v:avg(a,'training_hours')})),tm=Math.max(...ds.map(x=>x.v),1);$('#trainingBars').innerHTML=ds.map(x=>`<div class="train-col"><div class="train-bar" style="height:${x.v/tm*90}px"></div>${x.n}<br>${x.v.toFixed(0)}h</div>`).join('')}
function risk(r){let s=(r.overtime==='Yes'?25:0)+(+r.job_satisfaction<=2?25:0)+(+r.engagement_score<60?20:0)+(+r.absence_days>12?15:0)+(+r.years_at_company<2?10:0);return s>=55?'risk':s>=30?'watch':'stable'}
function people(){const q=$('#search').value.toLowerCase(),a=state.filtered.filter(r=>(r.employee_id+' '+r.job_role+' '+r.department).toLowerCase().includes(q)).slice(0,15);$('#peopleTable').innerHTML=a.map(r=>{const s=risk(r),label=s==='risk'?'High risk':s==='watch'?'Watch':'Stable';return `<tr><td><strong>${r.employee_id}</strong><br><small>${r.gender}, ${r.age}</small></td><td>${r.job_role}<br><small>${r.department}</small></td><td>${r.work_mode}</td><td>${r.years_at_company} years</td><td>${r.engagement_score}/100</td><td>${r.promotion_eligible==='Yes'?'Eligible':'Developing'}</td><td><span class="signal ${s}">${label}</span></td></tr>`}).join('')}
function actions(){const r=state.filtered,dept=Object.entries(grp(r,'department')).map(([n,a])=>({n,rate:a.filter(x=>x.attrition==='Yes').length/a.length*100})).sort((a,b)=>b.rate-a.rate)[0],abs=r.filter(x=>+x.absence_days>12).length,prom=r.filter(x=>x.promotion_eligible==='Yes').length;const a=[['Retention sprint',dept?`${dept.n} leads attrition at ${dept.rate.toFixed(1)}%. Run focused stay interviews and manager reviews.`:'No data'],['Wellbeing response',`${abs} employees have more than 12 absence days. Review workload, flexibility and wellbeing support.`],['Career pathways',`${prom} employees meet promotion-readiness criteria. Build succession slates before external hiring.`]];$('#insightCards').innerHTML=a.map(x=>`<div class="action"><strong>${x[0]}</strong><p>${x[1]}</p></div>`).join('')}
function exportData(){const h=Object.keys(state.rows[0]),out=[h.join(','),...state.filtered.map(r=>h.map(k=>r[k]).join(','))].join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([out],{type:'text/csv'}));a.download='hr_people_insights.csv';a.click()}
init();
