const state={rows:[],filtered:[]};
const $=id=>document.getElementById(id);
const parseCSV=text=>{const lines=text.trim().split(/\r?\n/);const headers=lines[0].split(',');return lines.slice(1).map(line=>{const values=line.split(',');return Object.fromEntries(headers.map((h,i)=>[h,values[i]??'']))})};
const number=v=>Number(v)||0;
const money=v=>new Intl.NumberFormat('en-IN',{notation:'compact',maximumFractionDigits:1}).format(v);
const group=(rows,key)=>rows.reduce((acc,row)=>{(acc[row[key]]??=[]).push(row);return acc},{});
const avg=(rows,key)=>rows.length?rows.reduce((s,r)=>s+number(r[key]),0)/rows.length:0;
function fillOptions(id,key){const el=$(id);[...new Set(state.rows.map(r=>r[key]))].sort().forEach(v=>el.add(new Option(v,v)))}
function kpis(rows){const completed=rows.filter(r=>r.status==='Completed');const ontime=completed.filter(r=>r.on_time==='Yes').length;const first=completed.filter(r=>r.first_pass_approved==='Yes').length;$('kpi-projects').textContent=rows.length.toLocaleString('en-IN');$('kpi-ontime').textContent=completed.length?`${(ontime/completed.length*100).toFixed(1)}%`:'—';$('kpi-firstpass').textContent=completed.length?`${(first/completed.length*100).toFixed(1)}%`:'—';$('kpi-quality').textContent=rows.length?avg(rows,'quality_score').toFixed(1):'—';$('kpi-savings').textContent=`₹${money(rows.reduce((s,r)=>s+number(r.cost_saved_inr),0))}`;$('record-count').textContent=`${rows.length.toLocaleString('en-IN')} of ${state.rows.length.toLocaleString('en-IN')} projects`}
function verticalChart(id,entries){const el=$(id);if(!entries.length){el.innerHTML='<p class="empty">No records match these filters.</p>';return}const max=Math.max(...entries.map(([,v])=>v),1);el.innerHTML=entries.map(([label,value])=>`<div class="bar-wrap"><span class="bar-value">${value}</span><div class="bar" style="height:${Math.max(3,value/max*82)}%" title="${label}: ${value}"></div><span class="bar-label">${label}</span></div>`).join('')}
function horizontalChart(id,entries,suffix=''){const el=$(id);if(!entries.length){el.innerHTML='<p class="empty">No data</p>';return}const max=Math.max(...entries.map(([,v])=>v),1);el.innerHTML=`<div class="hbar-list">${entries.map(([label,value])=>`<div class="hbar-row"><span>${label}</span><div class="hbar-track"><div class="hbar-fill" style="width:${value/max*100}%"></div></div><strong>${typeof value==='number'?value.toFixed(suffix?1:0):value}${suffix}</strong></div>`).join('')}</div>`}
function table(rows){const groups=group(rows,'content_type');$('content-table').innerHTML=Object.entries(groups).sort((a,b)=>b[1].length-a[1].length).map(([name,r])=>{const rework=r.filter(x=>number(x.revisions)>0).length/r.length*100;const saved=r.reduce((s,x)=>s+number(x.hours_saved),0);return `<tr><td>${name}</td><td>${r.length}</td><td>${avg(r,'quality_score').toFixed(1)}</td><td>${rework.toFixed(1)}%</td><td>${money(saved)}</td></tr>`}).join('')||'<tr><td colspan="5">No records match these filters.</td></tr>'}
function render(){const monthly=group(state.filtered.map(r=>({...r,month:r.created_date.slice(0,7)})),'month');verticalChart('trend-chart',Object.entries(monthly).sort().map(([m,r])=>[m,r.length]));horizontalChart('workflow-chart',Object.entries(group(state.filtered,'workflow')).map(([k,r])=>[k,avg(r,'quality_score')]).sort((a,b)=>b[1]-a[1]),'');horizontalChart('department-chart',Object.entries(group(state.filtered,'department')).map(([k,r])=>[k,r.length]).sort((a,b)=>b[1]-a[1]));kpis(state.filtered);table(state.filtered)}
function apply(){const filters=[['workflow-filter','workflow'],['department-filter','department'],['content-filter','content_type'],['status-filter','status']];state.filtered=state.rows.filter(row=>filters.every(([id,key])=>$(id).value==='All'||row[key]===$(id).value));render()}
async function init(){try{const response=await fetch('data/publishing_projects.csv');if(!response.ok)throw new Error('Data file unavailable');state.rows=parseCSV(await response.text());state.filtered=[...state.rows];fillOptions('workflow-filter','workflow');fillOptions('department-filter','department');fillOptions('content-filter','content_type');fillOptions('status-filter','status');['workflow-filter','department-filter','content-filter','status-filter'].forEach(id=>$(id).addEventListener('change',apply));$('reset-filters').addEventListener('click',()=>{['workflow-filter','department-filter','content-filter','status-filter'].forEach(id=>$(id).value='All');apply()});render()}catch(error){$('record-count').textContent='Run with a local server to load dashboard data';document.querySelectorAll('.chart').forEach(el=>el.innerHTML='<p class="empty">Start the project with: python -m http.server 8000</p>')}}
init();
