const state={rows:[],filtered:[],sort:{key:'otp',dir:-1}};
const $=s=>document.querySelector(s), fmt=n=>new Intl.NumberFormat('en-IN').format(Math.round(n)), avg=(a,k)=>a.length?a.reduce((s,r)=>s+(+r[k]||0),0)/a.length:0;
async function init(){try{const text=await fetch('data/airport_operations.csv').then(r=>{if(!r.ok)throw Error('Data file unavailable');return r.text()});state.rows=parseCSV(text);setup();render()}catch(e){$('#loading').innerHTML=`<strong>Unable to load dashboard data.</strong><br><small>${e.message}. Use a local web server instead of opening the file directly.</small>`}}
function parseCSV(text){const [h,...lines]=text.trim().split(/\r?\n/);const keys=h.split(',');return lines.map(line=>{const vals=line.split(',');return Object.fromEntries(keys.map((k,i)=>[k,vals[i]]))})}
function setup(){const dates=state.rows.map(r=>r.date).sort();$('#dateFrom').value=dates[0];$('#dateTo').value=dates.at(-1);for(const [id,key] of [['terminalFilter','terminal'],['airlineFilter','airline']]){[...new Set(state.rows.map(r=>r[key]))].sort().forEach(v=>$('#'+id).insertAdjacentHTML('beforeend',`<option>${v}</option>`))}document.querySelectorAll('.filters input,.filters select').forEach(x=>x.addEventListener('change',render));$('#resetBtn').onclick=()=>{setupValues();render()};$('#exportBtn').onclick=exportCSV;document.querySelectorAll('th[data-sort]').forEach(th=>th.onclick=()=>{const k=th.dataset.sort;state.sort={key:k,dir:state.sort.key===k?-state.sort.dir:-1};renderTable(groupAirlines(state.filtered))});$('#loading').hidden=true;$('#dashboard').hidden=false}
function setupValues(){const d=state.rows.map(r=>r.date).sort();$('#dateFrom').value=d[0];$('#dateTo').value=d.at(-1);$('#terminalFilter').value='All';$('#airlineFilter').value='All'}
function render(){const from=$('#dateFrom').value,to=$('#dateTo').value,t=$('#terminalFilter').value,a=$('#airlineFilter').value;state.filtered=state.rows.filter(r=>r.date>=from&&r.date<=to&&(t==='All'||r.terminal===t)&&(a==='All'||r.airline===a));renderKPIs();renderTrend();renderDelays();renderTerminals();renderHeatmap();renderTable(groupAirlines(state.filtered));renderInsights()}
function renderKPIs(){const r=state.filtered,pass=r.reduce((s,x)=>s+ +x.passengers,0),otp=r.length?r.filter(x=>+x.departure_delay_min<=15).length/r.length*100:0,load=r.length?pass/r.reduce((s,x)=>s+ +x.seat_capacity,0)*100:0;const items=[['✈','Total flights',fmt(r.length),'Flight movements'],['♟','Passengers',fmt(pass),'Processed volume'],['✓','On-time performance',otp.toFixed(1)+'%','≤15 min departure delay'],['◷','Average delay',avg(r,'departure_delay_min').toFixed(1)+' min','Departure reliability'],['⌛','Security wait',avg(r,'security_wait_min').toFixed(1)+' min','Average queue'],['▣','Load factor',load.toFixed(1)+'%','Seat utilization']];$('#overview').innerHTML=items.map(x=>`<article class="kpi"><div class="icon">${x[0]}</div><small>${x[1]}</small><strong>${x[2]}</strong><em>${x[3]}</em></article>`).join('')}
function by(rows,key){return rows.reduce((o,r)=>{(o[r[key]]??=[]).push(r);return o},{})}
function renderTrend(){const daily=Object.entries(by(state.filtered,'date')).sort().map(([date,r])=>({date,value:r.reduce((s,x)=>s+ +x.passengers,0)}));drawLine($('#trendChart'),daily);const mid=Math.max(1,Math.floor(daily.length/2)),first=avg(daily.slice(0,mid),'value'),last=avg(daily.slice(mid),'value'),chg=first?(last-first)/first*100:0;$('#trendChange').textContent=`${chg>=0?'↑':'↓'} ${Math.abs(chg).toFixed(1)}% period shift`}
function drawLine(canvas,data){const dpr=devicePixelRatio||1,w=canvas.clientWidth||700,h=260;canvas.width=w*dpr;canvas.height=h*dpr;const c=canvas.getContext('2d');c.scale(dpr,dpr);c.clearRect(0,0,w,h);const pad={l:42,r:15,t:15,b:30},max=Math.max(...data.map(d=>d.value),1),min=Math.min(...data.map(d=>d.value),0)*.92;c.strokeStyle='#20314a';c.fillStyle='#8fa5bf';c.font='10px Inter';for(let i=0;i<5;i++){const y=pad.t+(h-pad.t-pad.b)*i/4;c.beginPath();c.moveTo(pad.l,y);c.lineTo(w-pad.r,y);c.stroke();c.fillText(fmt(max-(max-min)*i/4),2,y+3)}if(!data.length)return;const pts=data.map((d,i)=>({x:pad.l+(w-pad.l-pad.r)*(i/Math.max(1,data.length-1)),y:pad.t+(h-pad.t-pad.b)*(1-(d.value-min)/(max-min||1))}));const grad=c.createLinearGradient(0,pad.t,0,h-pad.b);grad.addColorStop(0,'rgba(34,211,238,.28)');grad.addColorStop(1,'rgba(34,211,238,0)');c.beginPath();c.moveTo(pts[0].x,h-pad.b);pts.forEach(p=>c.lineTo(p.x,p.y));c.lineTo(pts.at(-1).x,h-pad.b);c.fillStyle=grad;c.fill();c.beginPath();pts.forEach((p,i)=>i?c.lineTo(p.x,p.y):c.moveTo(p.x,p.y));c.strokeStyle='#22d3ee';c.lineWidth=2;c.stroke();const step=Math.ceil(data.length/6);data.forEach((d,i)=>{if(i%step===0){c.fillStyle='#8fa5bf';c.fillText(d.date.slice(5),pts[i].x-13,h-8)}})}
function renderDelays(){const delayed=state.filtered.filter(r=>+r.departure_delay_min>15),groups=Object.entries(by(delayed,'delay_cause')).map(([name,r])=>({name,value:r.length})).sort((a,b)=>b.value-a.value),max=Math.max(...groups.map(x=>x.value),1);$('#delayChart').innerHTML=groups.map(x=>`<div class="bar-row"><span>${x.name}</span><div class="track"><div class="fill" style="width:${x.value/max*100}%"></div></div><strong>${delayed.length?(x.value/delayed.length*100).toFixed(0):0}%</strong></div>`).join('')||'<span class="muted">No delayed flights</span>'}
function renderTerminals(){const groups=Object.entries(by(state.filtered,'terminal')).map(([name,r])=>({name,pass:r.reduce((s,x)=>s+ +x.passengers,0),wait:avg(r,'security_wait_min')})).sort((a,b)=>b.pass-a.pass),max=Math.max(...groups.map(x=>x.pass),1);$('#terminalChart').innerHTML=groups.map(x=>`<div class="terminal-row"><span class="terminal-code">${x.name}</span><div><p>${fmt(x.pass)} passengers · ${x.wait.toFixed(1)} min security</p><div class="track"><div class="fill" style="width:${x.pass/max*100}%"></div></div></div><strong>${(x.pass/max*100).toFixed(0)}%</strong></div>`).join('')}
function renderHeatmap(){const hrs=Array.from({length:19},(_,i)=>i+5),g=by(state.filtered,'scheduled_departure'),vals=hrs.map(h=>state.filtered.filter(r=>+r.scheduled_departure.slice(0,2)===h).reduce((s,x)=>s+ +x.passengers,0)),max=Math.max(...vals,1);$('#heatmap').innerHTML=hrs.map((h,i)=>`<div><div class="heat-cell" title="${fmt(vals[i])} passengers" style="background:rgba(34,211,238,${.12+.82*vals[i]/max})">${fmt(vals[i])}</div><div class="heat-label">${String(h).padStart(2,'0')}:00</div></div>`).join('')}
function groupAirlines(rows){return Object.entries(by(rows,'airline')).map(([airline,r])=>{const cap=r.reduce((s,x)=>s+ +x.seat_capacity,0),pass=r.reduce((s,x)=>s+ +x.passengers,0);return{airline,flights:r.length,passengers:pass,otp:r.filter(x=>+x.departure_delay_min<=15).length/r.length*100,avgDelay:avg(r,'departure_delay_min'),load:pass/cap*100}})}
function renderTable(data){const {key,dir}=state.sort;data.sort((a,b)=>(a[key]>b[key]?1:a[key]<b[key]?-1:0)*dir);$('#airlineTable').innerHTML=data.map(x=>`<tr><td><strong>${x.airline}</strong></td><td>${fmt(x.flights)}</td><td>${fmt(x.passengers)}</td><td class="score">${x.otp.toFixed(1)}%</td><td>${x.avgDelay.toFixed(1)} min</td><td>${x.load.toFixed(1)}%</td></tr>`).join('')}
function renderInsights(){const r=state.filtered,air=groupAirlines(r).sort((a,b)=>b.otp-a.otp),term=Object.entries(by(r,'terminal')).map(([n,x])=>({n,wait:avg(x,'security_wait_min')})).sort((a,b)=>b.wait-a.wait),cause=Object.entries(by(r.filter(x=>+x.departure_delay_min>15),'delay_cause')).sort((a,b)=>b[1].length-a[1].length)[0];const insights=[['Reliability leader',air[0]?`${air[0].airline} leads filtered on-time performance at ${air[0].otp.toFixed(1)}%. Use its turnaround pattern as an internal benchmark.`:'No airline data.'],['Queue pressure',term[0]?`${term[0].n} has the highest security wait at ${term[0].wait.toFixed(1)} minutes. Review lane staffing during peak hours.`:'No terminal data.'],['Primary delay driver',cause?`${cause[0]} represents the largest delayed-flight category (${cause[1].length} flights). Prioritize the related mitigation playbook.`:'No material delays in this selection.']];$('#insightList').innerHTML=insights.map(x=>`<div class="insight"><strong>${x[0]}</strong><p>${x[1]}</p></div>`).join('')}
function exportCSV(){const h=Object.keys(state.rows[0]||{}),csv=[h.join(','),...state.filtered.map(r=>h.map(k=>r[k]).join(','))].join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='airport_filtered_data.csv';a.click();URL.revokeObjectURL(a.href)}
addEventListener('resize',()=>state.filtered.length&&renderTrend());init();
